version: '3.9'

services:
  # postgres:
  #   image: postgres:16-alpine
  #   ports:
  #     - 5432:5432
  # backend:
  #   build:
  #     context: ./backend
  frontend:
    build: ./frontend
    ports:
      - 8080:8080