version: '3.9'

services:
#   db:
#      image: postgres:16-alpine
#      restart: always
#      environment:
#        - POSTGRES_DB=db
#        - POSTGRES_USER=postgres
#        - POSTGRES_PASSWORD=postgres
#      ports:
#        - '5438:5432'
#      volumes:
#        - ./db:/var/lib/postgresql/data
   backend:
    build: ./backend
    ports:
      - 8082:8080
#    depends_on:
#      - db


#  frontend:
#    build: ./frontend
#    ports:
#      - 8080:8080