version: '3.9'

services:
  # postgres:
  #   image: postgres:16-alpine
  #   ports:
  #     - 5432:5432
  backend:
    build: ./backend
    ports:
      - 8081:8080
  frontend:
    build: ./frontend
    ports:
      - 8080:8080