name: Run Java tests with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up JDK 21 Temurin
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build and verify with Maven
      run: mvn -B verify --file pom.xml
    - name: Add coverage report to PR
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          ${{ github.workspace }}/**/target/site/jacoco-aggregate/jacoco.xml
        token: ${{ secrets.JACOCO_COVERAGE_TOKEN }}
        title: '# :raccoon: Test coverage'
        update-comment: true
        pass-emoji: ':green_heart:'
        fail-emoji: ':broken_heart:'
#       min-coverage-overall: 75
#       min-coverage-changed-files: 80